---
# tasks file for incube

- name: Install EPEL Repo
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present

- name: Import EPEL GPG key
  rpm_key:
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
    state: present

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest

- name: Install a list of packages
  yum:
    name:
      - screen
      - vim
      - htop
      - git
      - atop
      - ntp
      - unbound
      - monit
    state: present